In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [12]:
df=pd.read_csv('sample_data/qoute_dataset.csv')

In [13]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [14]:
df.shape

(3038, 2)

In [15]:
quotes=df['quote']

In [16]:
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [17]:
quotes=quotes.str.lower()

In [18]:
import string
translator=str.maketrans('','',string.punctuation)
quotes=quotes.apply(lambda x:x.translate(translator))

In [19]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [20]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [21]:
vocab_size=10000
token=Tokenizer(num_words=vocab_size)
token.fit_on_texts(quotes)

In [22]:
word_index=token.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [23]:
sequence=token.texts_to_sequences(quotes)

In [24]:
quotes[0]

'“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”'

In [25]:
sequence[0]

[713,
 62,
 29,
 19,
 16,
 946,
 10,
 7,
 5,
 1156,
 8,
 70,
 293,
 10,
 145,
 12,
 809,
 104,
 752,
 70,
 2461]

In [26]:

X=[]
y=[]

for seq in sequence:
  for i in range (1,len(seq)):
    X.append(seq[:i])
    y.append(seq[i])

In [27]:
len(X)

85271

In [28]:
len(y)

85271

In [29]:
max_len=max(len(x) for x in X)
print(max_len)

745

In [30]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [31]:
X_padded=pad_sequences(X,maxlen=max_len,padding='pre')

In [32]:
X_padded[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 713], dtype=int32)

In [33]:
y=np.array(y)

In [34]:
X_padded.shape

(85271, 745)

In [35]:
y.shape

(85271,)

In [36]:
from tensorflow.keras.utils import to_categorical
y_categorical = to_categorical(y, num_classes=vocab_size)
display(y_categorical.shape)

(85271, 10000)

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,SimpleRNN

In [38]:
embedding_dim=50
rnn_units=128

In [39]:
rnn_model=Sequential()
rnn_model.add(Embedding(vocab_size,embedding_dim,input_length=max_len-1))
rnn_model.add(SimpleRNN(rnn_units))
rnn_model.add(Dense(vocab_size,activation='softmax'))

In [37]:
rnn_model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [38]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
lstm_model=Sequential()
lstm_model.add(Embedding(vocab_size,embedding_dim,input_length=max_len))
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size,activation='softmax'))

In [40]:
lstm_model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [41]:
epochs=10
batch_size=128

In [42]:
history_rnn=rnn_model.fit(X_padded,y_categorical,epochs=epochs,batch_size=batch_size,validation_split=0.1)

Epoch 1/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 47s 71ms/step - accuracy: 0.0452 - loss: 6.7147 - val_accuracy: 0.0591 - val_loss: 6.5463
Epoch 2/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.0779 - loss: 6.1224 - val_accuracy: 0.0870 - val_loss: 6.3297
Epoch 3/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.1020 - loss: 5.7756 - val_accuracy: 0.0996 - val_loss: 6.2974
Epoch 4/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.1153 - loss: 5.5016 - val_accuracy: 0.1018 - val_loss: 6.3163
Epoch 5/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.1298 - loss: 5.2522 - val_accuracy: 0.1080 - val_loss: 6.3373
Epoch 6/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.1423 - loss: 5.0193 - val_accuracy: 0.1094 - val_loss: 6.4090
Epoch 7/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 66ms/step - accuracy: 0.1552 - loss: 4.7994 - val_accuracy: 0.1112 - val_loss: 6.4826
Epoch 8/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.1712 - loss: 4.5926 - val_accuracy: 0.1093 - val_loss: 6.5341
Epoch 9/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 66ms/step - accuracy: 0.1893 - loss: 4.3973 - val_accuracy: 0.1080 - val_loss: 6.6091
Epoch 10/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.2094 - loss: 4.2114 - val_accuracy: 0.1091 - val_loss: 6.6837

In [43]:
rnn_model.save('rnn_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [45]:
epochs=100
batch_size=128

history_lstm=lstm_model.fit(X_padded,y_categorical,epochs=epochs,batch_size=batch_size,validation_split=0.1)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 43s 59ms/step - accuracy: 0.0387 - loss: 6.7637 - val_accuracy: 0.0435 - val_loss: 6.6803
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0586 - loss: 6.3234 - val_accuracy: 0.0687 - val_loss: 6.5752
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0831 - loss: 6.0519 - val_accuracy: 0.0874 - val_loss: 6.4760
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1001 - loss: 5.8259 - val_accuracy: 0.0964 - val_loss: 6.4159
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1117 - loss: 5.6370 - val_accuracy: 0.1027 - val_loss: 6.4014
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1217 - loss: 5.4634 - val_accuracy: 0.1062 - val_loss: 6.4141
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1295 - loss: 5.3088 - val_accuracy: 0.1072 - val_loss: 6.4359
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1371 - loss: 5.1665 - val_accuracy: 0.1103 - val_loss: 6.4722
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1436 - loss: 5.0315 - val_accuracy: 0.1125 - val_loss: 6.5137
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1505 - loss: 4.9022 - val_accuracy: 0.1119 - val_loss: 6.5487
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1576 - loss: 4.7745 - val_accuracy: 0.1148 - val_loss: 6.6144
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1650 - loss: 4.6508 - val_accuracy: 0.1157 - val_loss: 6.6712
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1723 - loss: 4.5295 - val_accuracy: 0.1168 - val_loss: 6.7394
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.1810 - loss: 4.4098 - val_accuracy: 0.1176 - val_loss: 6.8091
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1929 - loss: 4.2920 - val_accuracy: 0.1155 - val_loss: 6.8848
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2054 - loss: 4.1762 - val_accuracy: 0.1154 - val_loss: 6.9590
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2194 - loss: 4.0661 - val_accuracy: 0.1141 - val_loss: 7.0482
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2331 - loss: 3.9595 - val_accuracy: 0.1135 - val_loss: 7.1022
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2463 - loss: 3.8587 - val_accuracy: 0.1139 - val_loss: 7.1905
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.2618 - loss: 3.7638 - val_accuracy: 0.1130 - val_loss: 7.2782
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 56ms/step - accuracy: 0.2746 - loss: 3.6743 - val_accuracy: 0.1112 - val_loss: 7.3460
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.2863 - loss: 3.5916 - val_accuracy: 0.1088 - val_loss: 7.4278
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2993 - loss: 3.5134 - val_accuracy: 0.1092 - val_loss: 7.5105
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.3100 - loss: 3.4401 - val_accuracy: 0.1080 - val_loss: 7.5973
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3211 - loss: 3.3710 - val_accuracy: 0.1073 - val_loss: 7.6623
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3314 - loss: 3.3051 - val_accuracy: 0.1044 - val_loss: 7.7400
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3411 - loss: 3.2411 - val_accuracy: 0.1066 - val_loss: 7.8197
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3516 - loss: 3.1806 - val_accuracy: 0.1024 - val_loss: 7.8817
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3625 - loss: 3.1215 - val_accuracy: 0.1019 - val_loss: 7.9565
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 55ms/step - accuracy: 0.3713 - loss: 3.0649 - val_accuracy: 0.1013 - val_loss: 8.0284
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.3794 - loss: 3.0113 - val_accuracy: 0.1019 - val_loss: 8.1010
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3896 - loss: 2.9583 - val_accuracy: 0.1001 - val_loss: 8.1571
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3981 - loss: 2.9073 - val_accuracy: 0.1011 - val_loss: 8.2312
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4069 - loss: 2.8576 - val_accuracy: 0.0974 - val_loss: 8.2851
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4152 - loss: 2.8091 - val_accuracy: 0.0969 - val_loss: 8.3500
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4223 - loss: 2.7647 - val_accuracy: 0.0978 - val_loss: 8.4225
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4304 - loss: 2.7195 - val_accuracy: 0.0951 - val_loss: 8.4745
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4391 - loss: 2.6752 - val_accuracy: 0.0960 - val_loss: 8.5575
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4460 - loss: 2.6353 - val_accuracy: 0.0955 - val_loss: 8.6130
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4540 - loss: 2.5910 - val_accuracy: 0.0958 - val_loss: 8.6658
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4629 - loss: 2.5511 - val_accuracy: 0.0951 - val_loss: 8.7399
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4675 - loss: 2.5131 - val_accuracy: 0.0938 - val_loss: 8.7963
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4754 - loss: 2.4744 - val_accuracy: 0.0945 - val_loss: 8.8614
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4820 - loss: 2.4372 - val_accuracy: 0.0908 - val_loss: 8.9155
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4882 - loss: 2.4016 - val_accuracy: 0.0920 - val_loss: 8.9806
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4954 - loss: 2.3671 - val_accuracy: 0.0920 - val_loss: 9.0349
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5007 - loss: 2.3317 - val_accuracy: 0.0905 - val_loss: 9.0874
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5079 - loss: 2.2977 - val_accuracy: 0.0912 - val_loss: 9.1660
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5135 - loss: 2.2656 - val_accuracy: 0.0895 - val_loss: 9.2243
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5201 - loss: 2.2332 - val_accuracy: 0.0911 - val_loss: 9.2598
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5256 - loss: 2.2022 - val_accuracy: 0.0904 - val_loss: 9.3312
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5314 - loss: 2.1712 - val_accuracy: 0.0892 - val_loss: 9.3908
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5387 - loss: 2.1406 - val_accuracy: 0.0896 - val_loss: 9.4371
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5432 - loss: 2.1125 - val_accuracy: 0.0857 - val_loss: 9.5102
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5487 - loss: 2.0851 - val_accuracy: 0.0874 - val_loss: 9.5559
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 55ms/step - accuracy: 0.5554 - loss: 2.0546 - val_accuracy: 0.0852 - val_loss: 9.6162
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5594 - loss: 2.0278 - val_accuracy: 0.0868 - val_loss: 9.6421
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5662 - loss: 2.0005 - val_accuracy: 0.0845 - val_loss: 9.7152
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5710 - loss: 1.9738 - val_accuracy: 0.0848 - val_loss: 9.7815
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5759 - loss: 1.9493 - val_accuracy: 0.0844 - val_loss: 9.8281
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5818 - loss: 1.9237 - val_accuracy: 0.0860 - val_loss: 9.8872
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5860 - loss: 1.9000 - val_accuracy: 0.0824 - val_loss: 9.9379
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5906 - loss: 1.8755 - val_accuracy: 0.0850 - val_loss: 9.9749
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5965 - loss: 1.8515 - val_accuracy: 0.0847 - val_loss: 10.0429
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6021 - loss: 1.8271 - val_accuracy: 0.0838 - val_loss: 10.0942
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6067 - loss: 1.8048 - val_accuracy: 0.0842 - val_loss: 10.1402
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6108 - loss: 1.7829 - val_accuracy: 0.0836 - val_loss: 10.2138
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6142 - loss: 1.7613 - val_accuracy: 0.0823 - val_loss: 10.2529
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6191 - loss: 1.7399 - val_accuracy: 0.0820 - val_loss: 10.3018
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6238 - loss: 1.7185 - val_accuracy: 0.0834 - val_loss: 10.3310
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6289 - loss: 1.6990 - val_accuracy: 0.0818 - val_loss: 10.3906
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6316 - loss: 1.6771 - val_accuracy: 0.0818 - val_loss: 10.4556
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6360 - loss: 1.6573 - val_accuracy: 0.0818 - val_loss: 10.5000
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6397 - loss: 1.6373 - val_accuracy: 0.0827 - val_loss: 10.5597
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6443 - loss: 1.6189 - val_accuracy: 0.0811 - val_loss: 10.5993
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 54ms/step - accuracy: 0.6476 - loss: 1.6004 - val_accuracy: 0.0803 - val_loss: 10.6485
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6518 - loss: 1.5824 - val_accuracy: 0.0800 - val_loss: 10.6891
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6548 - loss: 1.5636 - val_accuracy: 0.0797 - val_loss: 10.7595
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6602 - loss: 1.5462 - val_accuracy: 0.0779 - val_loss: 10.7918
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6648 - loss: 1.5281 - val_accuracy: 0.0803 - val_loss: 10.8672
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6666 - loss: 1.5124 - val_accuracy: 0.0807 - val_loss: 10.9283
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6697 - loss: 1.4958 - val_accuracy: 0.0794 - val_loss: 10.9631
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6746 - loss: 1.4773 - val_accuracy: 0.0774 - val_loss: 11.0070
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6775 - loss: 1.4623 - val_accuracy: 0.0777 - val_loss: 11.0559
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6815 - loss: 1.4456 - val_accuracy: 0.0782 - val_loss: 11.1153
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.6839 - loss: 1.4313 - val_accuracy: 0.0786 - val_loss: 11.1716
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.6873 - loss: 1.4163 - val_accuracy: 0.0776 - val_loss: 11.2022
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.6894 - loss: 1.4017 - val_accuracy: 0.0774 - val_loss: 11.2607
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6938 - loss: 1.3866 - val_accuracy: 0.0790 - val_loss: 11.3037
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6978 - loss: 1.3716 - val_accuracy: 0.0780 - val_loss: 11.3419
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7002 - loss: 1.3582 - val_accuracy: 0.0783 - val_loss: 11.4033
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7030 - loss: 1.3427 - val_accuracy: 0.0775 - val_loss: 11.4625
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7051 - loss: 1.3300 - val_accuracy: 0.0797 - val_loss: 11.5076
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7091 - loss: 1.3153 - val_accuracy: 0.0770 - val_loss: 11.5530
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7106 - loss: 1.3032 - val_accuracy: 0.0760 - val_loss: 11.5847
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7134 - loss: 1.2905 - val_accuracy: 0.0779 - val_loss: 11.6527
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7170 - loss: 1.2779 - val_accuracy: 0.0747 - val_loss: 11.7003
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7197 - loss: 1.2659 - val_accuracy: 0.0758 - val_loss: 11.7551
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7237 - loss: 1.2525 - val_accuracy: 0.0767 - val_loss: 11.7791
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7252 - loss: 1.2411 - val_accuracy: 0.0765 - val_loss: 11.8317

In [46]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [49]:
index_to_word={}

for word, index in word_index.items():
  index_to_word[index] = word

In [50]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [51]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [68]:
seed_text = "i want to have"
next_word = predictor(lstm_model,token,seed_text,max_len)
print(next_word)

the

In [69]:

def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [70]:
seed = "did you  "
generate_text = generate_text(lstm_model,token,seed,max_len,10)
print(generate_text)

did you   remember the book thief many things that you can never

In [72]:
import pickle

In [73]:
with open("tokenizer.pickle","wb") as f:
  pickle.dump(token,f)

In [74]:
with open("max_len.pickle","wb") as f:
  pickle.dump(max_len,f)

In [1]:
from tensorflow.keras.layers import Embedding, GRU, Dense, Dropout